language: node_js
node_js:
  - "8.2.1"
script:
  - npm run build
  - sonar-scanner
addons:
  sonarcloud:
    organization: "vaneyck-github"
    token:
      secure: RxFGobNXzIs3AuqgFIc2XC0C9z+9HWItOBuFG78waLcI8OdmOy8j2iPa6HUZGDn/Dsuw4IbJSSLiUHeFsket/SF4RldXtq7R64397I7sxHt/4Kew1SFsuwczlR/ViqzlR7WloWxW2+oReot5kQ2smSVSOS8Wdhg9XsrPQJnwGc89AkzYaPTnyt8QCiJGRN+I070MpCXsbTstPvddWoSOyu3n3j3VShR3NxFZABHxm4tdYLhKwv/izP/xlpNpLKKOIyngQAvWvD7WitC8SBNpxesR/qYWCIAhxBmct5Tw4utZ+/BKOYSzWFrHFLf3SaGnEFQzGPVWuFeFvxQXVk9iz+VGJbqIEInR/FjX7rO9x74KflMF/f0Iu0RjAHcGR6DOqhLRx18pDiLYxukESrcAVCprIxTSksNqMIvk6TJiBGGl1fW9Q4i8nBJVsuBEENR3OK9l27PO+2KEeVhBCeJtu9sWsdf3/LZJGWDkyWZWSr7X4OhkKtAmlijZfx63J9oa8x1M9sxbc0FJV59hxKn/8QmKmCU+avxjcElH71Sy9qv0gL5s5Ag4RftE9PAy1Ua99YsvrXz75QnIrErRRf6YUTpG2zREzLDn0XjWT1/8XJJvFyOrP0pzSZ7lYWo3YThRBayvlOewW3wHKdztlT4vWZxwIO/6vxC4kx7svdRlEXc=